import pygame

START_GAME = pygame.K_SPACE

PADDLE_1_UP = pygame.K_w
PADDLE_1_DOWN = pygame.K_s
PADDLE_2_UP = pygame.K_UP
PADDLE_2_DOWN = pygame.K_DOWN

CHANGE_MODE_UP = pygame.K_UP
CHANGE_MODE_DOWN = pygame.K_DOWN
CHANGE_DIF_UP = pygame.K_RIGHT
CHANGE_DIF_DOWN = pygame.K_LEFT

PAUSE_GAME = pygame.K_ESCAPE
QUIT_GAME = pygame.K_RETURN
QUIT_PROGRAM = pygame.K_BACKSPACE
CANCEL_CONNECTION_AWAIT = pygame.K_ESCAPE
